FROM centos:7
MAINTAINER sunwenju
RUN yum install epel-release -y && \
    yum install -y gcc gcc-c++ make gd-devel libxml2-devel \
    libcurl-devel libjpeg-devel libpng-devel openssl-devel \
    libmcrypt-devel libxslt-devel libtidy-devel autoconf \
    iproute net-tools telnet wget curl \
	perl kernel-headers kernel-devel vim && \
    yum clean all && \
    rm -rf /var/cache/yum/*
RUN cd && \
    curl -O 'https://libzip.org/download/libzip-1.3.2.tar.gz'  && \
    tar zxf libzip-1.3.2.tar.gz && \
	cd libzip-1.3.2/  && \
	./configure && make && make install && \
	echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf  && \
	ldconfig
RUN cd && \
    yum -y install epel-release && \
    yum -y install gcc gcc-c++ make pcre pcre-devel zlib zlib-devel openssl \
	openssl-devel libxml2 libxml2-devel libcurl libcurl-devel libjpeg libjpeg-devel \
	libpng libpng-devel freetype freetype-devel openldap openldap-devel libmcrypt \
	libmcrypt-devel && \
	wget https://www.php.net/distributions/php-7.3.16.tar.gz && \
	tar zxf php-7.3.16.tar.gz && \
	cd php-7.3.16 && \
	./configure --prefix=/usr/local/php --with-config-file-path=/usr/local/php/etc --enable-ctype \
	--with-mysql=mysqlnd --with-mysqli=mysqlnd --with-freetype-dir --with-jpeg-dir --with-png-dir \
	--with-zlib --with-libxml-dir=/usr --enable-xml --disable-rpath --enable-bcmath --enable-shmop \
	--enable-sysvsem --enable-inline-optimization --with-curl --enable-mbregex --enable-mbstring \
	--with-mcrypt --with-gd --enable-gd-native-ttf --with-openssl --with-mhash --enable-pcntl \
	--enable-sockets --with-ldap-sasl --with-xmlrpc --enable-zip --enable-soap --with-gettext --enable-fpm && \
	make -j 2 && make install && \
	cp php.ini-production /usr/local/php/etc/php.ini && \
        cp sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm && \
	chmod +x /etc/init.d/php-fpm && \
	cd /usr/local/php/etc/ && \
	mv php-fpm.conf.default php-fpm.conf && \
	cd  /usr/local/php/etc/php-fpm.d/  && \
	mv www.conf.default www.conf 
	
ENV PATH $PATH:/usr/local/php/sbin
COPY php.ini /usr/local/php/etc/
COPY php-fpm.conf /usr/local/php/etc/
COPY www.conf /usr/local/php/etc/php-fpm.d/
RUN rm -rf /root/*  
EXPOSE 9000
CMD ["/usr/local/php/sbin/php-fpm","-F","-R"]
