FROM centos:7
MAINTAINER sunwenju
RUN yum install -y gcc wget gcc-c++ make \
    openssl-devel pcre-devel gd-devel \
    iproute net-tools telnet wget curl unzip perl kernel-headers kernel-devel vim && \
    yum clean all && \
    rm -rf /var/cache/yum/*
RUN yum -y install gcc make pcre pcre-devel zlib zlib-devel openssl-devel  readline-devel && \
    cd && \
    wget https://openresty.org/download/openresty-1.15.8.1.tar.gz  && \
    tar zxf openresty-1.15.8.1.tar.gz && \
    cd openresty-1.15.8.1 && \
    ./configure --prefix=/usr/local/openresty \
    --with-http_stub_status_module \
    --with-http_ssl_module \
    --with-stream	&& \
    make -j 2 && make install && \
	ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
	cd && \
	wget https://github.com/unixhot/waf/archive/v1.0.0.tar.gz && \
	tar zxf v1.0.0.tar.gz && \
	cp -r waf-1.0.0/waf /usr/local/openresty/nginx/conf/ && \
        mkdir -p /usr/local/openresty/nginx/conf/{vhosts,ssl} && \
        mkdir -p /usr/local/openresty/nginx/downloads && \
		groupadd nginx && \
		useradd -g nginx -s /sbin/nologin nginx  
ENV PATH $PATH:/usr/local/openresty/nginx/sbin
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY osce.conf /usr/local/openresty/nginx/conf/vhosts/osce.conf
COPY www.wenjusir.cn.key  /usr/local/openresty/nginx/conf/ssl/www.wenjusir.cn.key
COPY www.wenjusir.cn.pem  /usr/local/openresty/nginx/conf/ssl/www.wenjusir.cn.pem

RUN yum install epel-release -y && \
    yum install -y gcc gcc-c++ make gd-devel libxml2-devel \
    libcurl-devel libjpeg-devel libpng-devel openssl-devel \
    libmcrypt-devel libxslt-devel libtidy-devel autoconf \
    iproute net-tools telnet wget curl \
	perl kernel-headers kernel-devel vim && \
    yum clean all && \
    rm -rf /var/cache/yum/*
RUN cd && \
    curl -O 'https://libzip.org/download/libzip-1.3.2.tar.gz'  && \
    tar zxf libzip-1.3.2.tar.gz && \
	cd libzip-1.3.2/  && \
	./configure && make && make install && \
	echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf  && \
	ldconfig
RUN cd && \
    yum -y install epel-release && \
    yum -y install gcc gcc-c++ make pcre pcre-devel zlib zlib-devel openssl \
	openssl-devel libxml2 libxml2-devel libcurl libcurl-devel libjpeg libjpeg-devel \
	libpng libpng-devel freetype freetype-devel openldap openldap-devel libmcrypt \
	libmcrypt-devel && \
	wget https://www.php.net/distributions/php-7.3.16.tar.gz && \
	tar zxf php-7.3.16.tar.gz && \
	cd php-7.3.16 && \
	./configure --prefix=/usr/local/php --with-config-file-path=/usr/local/php/etc --enable-ctype \
	--with-mysql=mysqlnd --with-mysqli=mysqlnd --with-freetype-dir --with-jpeg-dir --with-png-dir \
	--with-zlib --with-libxml-dir=/usr --enable-xml --disable-rpath --enable-bcmath --enable-shmop \
	--enable-sysvsem --enable-inline-optimization --with-curl --enable-mbregex --enable-mbstring \
	--with-mcrypt --with-gd --enable-gd-native-ttf --with-openssl --with-mhash --enable-pcntl \
	--enable-sockets --with-ldap-sasl --with-xmlrpc --enable-zip --enable-soap --with-gettext --enable-fpm && \
	make -j 2 && make install && \
	cp php.ini-production /usr/local/php/etc/php.ini && \
        cp sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm && \
	chmod +x /etc/init.d/php-fpm && \
	cd /usr/local/php/etc/ && \
	mv php-fpm.conf.default php-fpm.conf && \
	cd  /usr/local/php/etc/php-fpm.d/  && \
	mv www.conf.default www.conf 
	
ENV PATH $PATH:/usr/local/php/sbin
COPY php.ini /usr/local/php/etc/
COPY php-fpm.conf /usr/local/php/etc/
COPY www.conf /usr/local/php/etc/php-fpm.d/

COPY run.sh /tmp/run.sh
RUN chmod +x /tmp/run.sh
EXPOSE 80 443 9000
CMD ["/tmp/run.sh"]
